name: Sync Folder from repo1 to repo2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo2 (target-repo)
        uses: actions/checkout@v2
        with:
          repository: kotaRaghav/oddtarget-repo2
          ref: main
          token: ${{ secrets.REPO2_TOKEN }}

      - name: Checkout repo1 (source-repo)
        uses: actions/checkout@v2
        with:
          repository: kotaRaghav/oddsource-repo1
          ref: main
          token: ${{ secrets.REPO1_TOKEN }}

      - name: Copy files from repo1 to repo2
        run: |
          cp -r odd-folder-sync/* repo2/sync-folder/

      - name: Commit and push changes to repo2
        run: |
          git config --global user.name "kotaRaghav"
          git config --global user.email "raghavendraasdf@gmail.com"
          git add .
          git commit -m "Sync files from repo1 to repo2"
          git push origin main
